# Generated by Django 6.0.3 on 2026-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('style', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, default='', max_length=120)),
                ('occasion', models.CharField(blank=True, default='', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
